stages:
  - build
  - deploy

build:
  stage: build
  script:
    - node -v
    - npm -v
    - npm install

deploy_to_render:
  stage: deploy
  only:
    - main
  script:
    - echo "Triggering Render deploy"
    - curl -X POST "$RENDER_DEPLOY_HOOK"